// Cities surrounding ETI Educom Pathankot HQ — used for programmatic SEO landing pages
// Add or edit cities here and they automatically generate /courses/[program]-course-in-[city] pages
// AND get added to /location-sitemap.xml.

export const LOCATIONS = [
  {
    slug: 'pathankot',
    name: 'Pathankot',
    state: 'Punjab',
    stateShort: 'Punjab',
    distanceKm: 0,
    landmark: 'our flagship campus on Dhangu Road',
    pin: '145001',
    nearby: 'Mamoon Cantt, Sujanpur, Suratgarh',
  },
  {
    slug: 'gurdaspur',
    name: 'Gurdaspur',
    state: 'Punjab',
    stateShort: 'Punjab',
    distanceKm: 29,
    landmark: 'Hanuman Chowk',
    pin: '143521',
    nearby: 'Dinanagar, Dhariwal, Kahnuwan',
  },
  {
    slug: 'batala',
    name: 'Batala',
    state: 'Punjab',
    stateShort: 'Punjab',
    distanceKm: 85,
    landmark: 'Anand Cinema Road',
    pin: '143505',
    nearby: 'Qadian, Fatehgarh Churian',
  },
  {
    slug: 'amritsar',
    name: 'Amritsar',
    state: 'Punjab',
    stateShort: 'Punjab',
    distanceKm: 110,
    landmark: 'Hall Bazaar',
    pin: '143001',
    nearby: 'Ajnala, Tarn Taran, Beas',
  },
  {
    slug: 'dalhousie',
    name: 'Dalhousie',
    state: 'Himachal Pradesh',
    stateShort: 'HP',
    distanceKm: 80,
    landmark: 'Gandhi Chowk',
    pin: '176304',
    nearby: 'Khajjiar, Banikhet, Bakloh',
  },
  {
    slug: 'chamba',
    name: 'Chamba',
    state: 'Himachal Pradesh',
    stateShort: 'HP',
    distanceKm: 120,
    landmark: 'Chowgan Ground',
    pin: '176310',
    nearby: 'Bharmour, Tissa, Salooni',
  },
  {
    slug: 'nurpur',
    name: 'Nurpur',
    state: 'Himachal Pradesh',
    stateShort: 'HP',
    distanceKm: 25,
    landmark: 'Nurpur Fort',
    pin: '176202',
    nearby: 'Kotla, Indora, Jawali',
  },
  {
    slug: 'jammu',
    name: 'Jammu',
    state: 'Jammu & Kashmir',
    stateShort: 'J&K',
    distanceKm: 110,
    landmark: 'Raghunath Bazaar',
    pin: '180001',
    nearby: 'Akhnoor, Vijaypur, Ranbir Singh Pura',
  },
  {
    slug: 'kathua',
    name: 'Kathua',
    state: 'Jammu & Kashmir',
    stateShort: 'J&K',
    distanceKm: 42,
    landmark: 'Kathua Bus Stand',
    pin: '184101',
    nearby: 'Hiranagar, Lakhanpur, Basohli',
  },
  {
    slug: 'udhampur',
    name: 'Udhampur',
    state: 'Jammu & Kashmir',
    stateShort: 'J&K',
    distanceKm: 180,
    landmark: 'Salathia Chowk',
    pin: '182101',
    nearby: 'Ramnagar, Chenani, Reasi',
  },
];

export const LOCATION_BY_SLUG = Object.fromEntries(LOCATIONS.map((l) => [l.slug, l]));

export const LOCATION_SLUGS = LOCATIONS.map((l) => l.slug);
